### ISSUE TITLE
Can't load libpdplusplus.dylib

### ISSUE THREAD

**Issue by Garrettlynch** [robertesler/Pd4P3#10]
Looks very interesting but I can't load library in Processing 4 on OSX (Intel, 10.14). I get:

```
UnsatisfiedLinkError: /Users/me/Documents/Processing/libraries/Pd4P3/library/libpdplusplus.dylib: dlopen(/Users/garrettlynch/Documents/Processing/libraries/Pd4P3/library/libpdplusplus.dylib, 1): no suitable image found.  Did find:
	/Users/me/Documents/Processing/libraries/Pd4P3/library/libpdplusplus.dylib: cannot load 'libpdplusplus.dylib' (load command 0x80000034 is unknown)
```

Is there a fix?

**Comment by robertesler** [comment]
That means the dynamic library wasn't built for your computer's architecture.  I can fix it in an update but can't get to that for at least a week, or until I get in front of a Mac, I'm more Windows/Linux.  Right now if you want the most recent bug updates, a fix would be to build the .dylib yourself then replace it in the Processing folder.  The source code for Pd++ is here, https://bitbucket.org/resler/pd/src/master/.
After you download or clone it use the Terminal app to `cd` into the Pd++ folder.  Then type `make`.  You need to look at the Makefile and change the JNI paths to wherever the Java JDK is installed on your system.  If none of this makes sense then you could try downloading an older stable release from GitHub here: https://github.com/robertesler/Pd4P3/releases
V 0.0.8 should work on both Intel and M1+ Mac chips.   Just replace the download with the current folder in the Processing/libraries folder.

**Comment by robertesler** [comment]
The Rpi build instructions are the same for MacOS so for now if you need more information check here:
https://github.com/robertesler/Pd4P3?tab=readme-ov-file#build-for-the-raspberry-pi
I will update the Mac binaries by the end of next week.

**Comment by Garrettlynch** [comment]
> I can fix it in an update but can't get to that for at least a week, or until I get in front of a Mac,

Yes understood. Maintaining things across platforms can be a pain. Will try an older version first as I mainly want to play with this. Have been looking for a way to do audio synthesis in Processing at the level it can be done in Puredata (and is student accessible) and apart from using OSC to communicate between the two this would be my go to. Many thanks. Look forward to the fix/update.

**Comment by Garrettlynch** [comment]
>V 0.0.8 should work on both Intel and M1+ Mac chips. Just replace the download with the current folder in the Processing/libraries folder.

Yes v 0.0.8 has x86 but I get a completely different issue when I swap the Pd4P3 folder for the Pd4P3-nature folder (and changed the name).

```
No library found for com.pdplusplus
Libraries must be installed in a folder named 'libraries' inside the sketchbook folder (see the Preferences window).
The package “com.pdplusplus” does not exist. You might be missing a library.
```
I tried putting the contents of src into the sketches libraries folder, like this:

![Screenshot 2024-07-09 at 14 30 39](https://github.com/robertesler/Pd4P3/assets/8354239/f3f55896-2029-4ac3-9eb9-0ad728572674)

but no luck, same error.

**Comment by robertesler** [comment]
I probably should have asked this at the beginning but what is your Mac model and OS?   The odd thing is I test on an Intel Mac and it works fine. It's the M1s I have to seek out to test.  Do you have and Intel or M1 Mac?

This error is because the GitHub versions don't include the .jar file, but there is an ant build script included that can build the Java library.   In the main directory would be `ant build` and it should produce the .jar file.  

But let me know your machine and OS.  I'm thinking something else is going on.

**Comment by Garrettlynch** [comment]
I mentioned this in the first message - Processing 4 on OSX (Intel, 10.14).

**Comment by robertesler** [comment]
Ah, ok I see that now.  I suspect that it's not an issue with the library but rather the version of your OS.  I believe Apple no longer supports Mojave so most likely when I built the library for MacOS the minimum OS is higher than your version, probably 10.15 or higher.  
So in that case you would need to follow the building for Rpi instructions to get a .dylib built for your OS and architecture. 
You can find that here: https://github.com/robertesler/Pd4P3?tab=readme-ov-file#build-for-the-raspberry-pi
I'll leave this issue open for now.  
I can look into building for older MacOS versions to support legacy hardware but can't promise anything at the moment.

**Comment by Garrettlynch** [comment]
> Ah, ok I see that now. I suspect that it's not an issue with the library but rather the version of your OS. I believe Apple no longer supports Mojave so most likely when I built the library for MacOS the minimum OS is higher than your version, probably 10.15 or higher. 

10.14 is the highest you can go on updates, 10.15 is a paid update, so lots of intel mac people are still on this. M1's in particular broke a lot of things. I have access to an M1 for work and everything works fine there.

**Comment by Garrettlynch** [comment]
Trying to build this today and following your instructions here (https://github.com/robertesler/Pd4P3?tab=readme-ov-file#build-for-the-raspberry-pi) but stuck on step 3, the path to change for OSX. 

This is my version of Java:
```
java version "16.0.2" 2021-07-20
Java(TM) SE Runtime Environment (build 16.0.2+7-67)
Java HotSpot(TM) 64-Bit Server VM (build 16.0.2+7-67, mixed mode, sharing)
```
and it's installed here:
`/usr/bin/java`

Should I be changing this `/usr/lib/jvm/java-1.11.0-openjdk-amd64/include/` to this `/Library/Java/JavaVirtualMachines/jdk-16.0.2.jdk` or this `/usr/bin/java`?

**Comment by Garrettlynch** [comment]
Ok so I miss-read, I'm building a .dylib file so it's the part of the make under Darwin that I need to change and from the comment there I guess I am pointing the path to `/Library/Java/JavaVirtualMachines/jdk-16.0.1.jdk/Contents/Home/include`. That's done but making the file has a fatal error:

`In file included from .//JNI/com_pdplusplus_RealZeroReverse.h:2:
/Library/Java/JavaVirtualMachines/jdk-16.0.2.jdk/Contents/Home/include/jni.h:45:10: fatal error: 
      'jni_md.h' file not found`

There are only these in the include folder:
```
classfile_constants.h	jdwpTransport.h		jvmticmlr.h
darwin			jni.h
jawt.h			jvmti.h
```

**Comment by robertesler** [comment]
The `jni_md.h` should be in the `/darwin` folder.  Try changing line 9 in the Makefile to `/Library/Java/JavaVirtualMachines/jdk-16.0.1.jdk/Contents/Home/include/darwin`

**Comment by Garrettlynch** [comment]
Ah I see, there are pathways to both of these files. I forgot to update the path of the md file. Ok that's built without any errors:

```
Bindings		MyClasses		PdMaster
JNI			Pd++Classes		libpdplusplus.dylib
```

I swapped the `libpdplusplus.dylib` in the Pd4p3 > library folder for the new built one. When I test the oscillator example I am back to the issue:

```
No library found for com.pdplusplus
Libraries must be installed in a folder named 'libraries' inside the sketchbook folder (see the Preferences window).
The package “com.pdplusplus” does not exist. You might be missing a library.
```

I didn't fully understand your solution here - "This error is because the GitHub versions don't include the .jar file, but there is an ant build script included that can build the Java library. In the main directory would be ant build and it should produce the .jar file.". Where is the ant build?

**Comment by robertesler** [comment]
That shouldn't be necessary now.  I think the error is because I earlier advised using an older version from GitHub which doesn't include the .jar file for the library. 

If you install the Pd4P3 library via Processing's Contribution Manager, then replace the .dylib you built with the one in the distribution then hopefully everything should work.

If for some reason you have to also compile the Java files, respond to this issue and I'll elaborate more.

**Comment by Garrettlynch** [comment]
wahoo, yes working, no issues. Many thanks for your help. I've attached the OSX 10.14 dylib I built. It might save you a bit of time and hassle getting to an intel mac. 

![Screenshot 2024-07-15 at 12 29 13](https://github.com/user-attachments/assets/fe1f9b11-b07a-41d4-9e4f-4045ea26dce0)

[libpdplusplus.dylib.zip](https://github.com/user-attachments/files/16233767/libpdplusplus.dylib.zip)

**Comment by robertesler** [comment]
That's great news!  Thanks for the build.  I might just toss into the repository as a legacy build, I will look further into build options for older versions of Mac.  But at least I know that it will build on older systems and can provide clearer instructions in the README.md.  Thanks for your diligence and testing.  I'll close this for now and open a new issue regarding legacy builds.
