### ISSUE TITLE
Pd4P3 and Android mode

### ISSUE THREAD

**Issue by dfkettle** [robertesler/Pd4P3#4]
Hi! Just a question: does Pd4P3 work in Android mode? If not, any plans to add support for Android mode? Thanks.

**Comment by robertesler** [comment]
Hi David, 

  Good to hear from you!  I have not yet looked into Android mode for
Processing, so my guess is as it stands now Pd4P3 won't work in Android
mode.  But I'll dig deeper into how that mode works and see if it is
something that could be added.   

  I appreciate the feedback and will look into adding this enhancement. 
Thank you. 

-Rob

On 2022-10-19 06:26, David Kettle wrote:

> Hi! Just a question: does Pd4P3 work in Android mode? If not, any plans to add support for Android mode? Thanks. 
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].
> You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
 

Links:
------
[1] https://github.com/robertesler/Pd4P3/issues/4
[2]

**Comment by dfkettle** [comment]
Thanks! I look forward to hearing more. If you need any help testing, let me know. I have a Samsung Galaxy Tab6 Lite (a tablet running Android 12) and a Samsung Galaxy Note 8 (a phone running Android 9) I can test with.

**Comment by robertesler** [comment]
@dfkettle  As of version 0.0.6 I have added Android mode support.  Getting started is a bit different than Java mode, so there are some examples in the examples/Android folder.  The audio/dsp side however is the same, or at least should be.

**Comment by robertesler** [comment]
It looks like I forgot to commit that file.  I'll fix it on the repo and the release.  Sorry about that.  It is just another class, or tab, in Processing. But I'll fix the sketch so it actually works.  Thanks for testing it, and finding that error.
