### ISSUE TITLE
[Android mode] Result of call to 'requestPermission()' ignored

### ISSUE THREAD

**Issue by dfkettle** [robertesler/Pd4P3#6]
I tried to port one of the examples that uses the microphone (Oscilloscope.pde) to Android, but it seems that the result of the call to  'requestPermission()' is being ignored. I modified the function as follows, and it printed "false" in the console log. I'm not sure why it's failing, but it's probably good practice to check the result of the call and not just assume it was successful.

```
private void requestRecordPermission(){
  requestPermission("android.permission.RECORD_AUDIO","permissionRequested");
}

public void permissionRequested(boolean granted) {
  println("record permission granted: ",granted);
}
```

As for why it failed (I wasn't prompted to grant permission), do I need to add something to manifest or the sketch properties?

**Comment by robertesler** [comment]
In Processing Android mode you have to add the permissions to your manifest via "Android - > Sketch Permissions", then select RECORD_AUDIO.  It should work after that.  If it doesn't let me know.

**Comment by dfkettle** [comment]
> In Processing Android mode you have to add the permissions to your manifest via "Android - > Sketch Permissions", then select RECORD_AUDIO. It should work after that. If it doesn't let me know.

Thanks, it's working now. The latency is quite noticeable when I use the microphone, but I guess that's because of the speed of the processor in my tablet (a Samsung Galaxy Tab 6 Lite). I might try it with a USB audio interface to see if it's any faster, though.

Here's the sketch, modified for Android, if you want to add it to your examples. I haven't modified it to make use of a pop-up virtual keyboard, though. I just tested it with a Bluetooth keyboard.

[AndroidManifest.xml.txt](https://github.com/robertesler/Pd4P3/files/10252154/AndroidManifest.xml.txt)
[Oscilloscope.pde.txt](https://github.com/robertesler/Pd4P3/files/10252155/Oscilloscope.pde.txt)
