### ISSUE TITLE
Microphone frequency 

### ISSUE THREAD

**Issue by jafal633** [robertesler/Pd4P3#8]
Hi sir 

Can you provide example how to measure microphone frequency

Thanks in advance

**Comment by robertesler** [comment]
Hi @jafal633!  In the provided examples the SigmundDemo does this already.  https://github.com/robertesler/Pd4P3/tree/main/examples/Analysis/SigmundDemo
The Sigmund class is a very powerful analysis tool.  You can look at all sinusoidal components detected or just calculate the pitch.   In the example it is calculating the loudest 10 sinusoidal components (or harmonics) from the microphone input.  Sigmund has two modes, peaks or pitch.  They return different values depending on which you choose.  So the code would look like this:
`Sigmund sig = new Sigmund("pitch", "env");` for pitch (in MIDI #) and envelope (in dB). 
`Sigmund sig = new Sigmund("peaks", 10);` for sinusoidal peaks.  This will provide the 10 loudest in a list of 5 values (see the Analysis class in the example for more information).
